

## Module 5 - Assignment 2
## Subramanian, Subbu
## More Data Wrangling

```{r Importing Data}

library(tidyverse)
library(readr)
tuition_cost <- read_csv("tuition_cost.csv")

```

## Part 1 – Creating tidy data using tidyr

```{r Tidy Data}
Tuition <- pivot_longer(tuition_cost,c('2017','2018','2019','2020'),names_to="year",values_to="tuition")
Tuition<-separate(Tuition, col=tuition, into=c('InState','OutState'), sep="/")
Tuition$InState<-as.integer(Tuition$InState)
Tuition$OutState<-as.integer(Tuition$OutState)
as.tibble(Tuition)

```


## Part 2 – North Carolina Schools

```{r NC Schools}

Public <- Tuition %>%
 select(name,state,state_code,type,degree_length,year,InState,OutState) %>%
 filter(state == "North Carolina" & degree_length == "4 Year" & type == "Public")


  ggplot(data=Public, aes(x=year,y=InState,color=name)) +
  geom_point() +
  labs(title = "In-State Tuition for North Carolina Schools", x = "Year", y="Cost in $")
  
UNC <- filter(Public,grepl("University of North Carolina",name))

  ggplot(data=UNC, aes(x=year,y=InState,color=name)) +
  geom_point() +
  labs(title = "In-State Tuition for North UNC Schools", x = "Year", y="Cost in $") +
    theme(legend.position="bottom") +
guides(colour = guide_legend(nrow = 4))
 
```

## Part 3 – Additional Universities

```{r Additional Universities}
Colorado <- Tuition %>%
 select(name,state,state_code,type,degree_length,year,InState,OutState) %>%
 filter(state == "Colorado" & degree_length == "4 Year" & type == "Private")


  ggplot(data=Colorado, aes(x=year,y=OutState,color=name)) +
  geom_point() +
  labs(title = "Out-State Tuition for Colorado Schools", x = "Year", y="Cost in $")
  
SouthCarolina <- Tuition %>%
 select(name,state,state_code,type,degree_length,year,InState,OutState) %>%
 filter(state == "South Carolina" & degree_length == "2 Year" & type == "Public")


  ggplot(data=SouthCarolina, aes(x=year,y=OutState,color=name)) +
  geom_point() +
  labs(title = "In-State Tuition for South Carolina Schools", x = "Year", y="Cost in $") +
         theme(legend.position="bottom") +
guides(colour = guide_legend(nrow = 10))
```

